### PR TITLE
Websitenew

### PR DESCRIPTION
**Pull request by philorilla**
added about, past and soundaroundyou.html to test internal linking of the navbar. changed title of index.html to "WUEST". Tested width of footer.

### CODE REVIEW

**Comment by philorilla** [comment]
Styled the footer. Added Nav disappers on scroll - still a bit buggy on mobile when button gets used. changed size of content boxes for different layout. added intro section with same size as content boxes.

**Comment by softbobo** [comment]
Hi! Very good job so far. Probs on the clean coding style @philorilla. Also the new design looks ace. Two comments on the UI:
* In the 'about' section there are two containers on ROUTINES where imho should be none but just info about WUEST in general. Is this on purpose?
* I am a bit torn apart on the shadows for the text boxes and would prefer them without shading, but this is a mere question of personal taste, so feel free to do whatever you like in this regard.

A few more remarks regarding our workflow:
* I deleted two dangling html documents we were no longer using and commited this. Please don't keep any renamed files of older versions, just change or delete them. This is one reason why we are using version control: if we need a former version of our project, we check out a former commit. Unused files just clutter our repo. I am more than happy to help if you have any questions regarding this.
*  At the moment, we keep images in version control. Right now this is feasible since we are not using too many. However, it is considered good practice to keep binaries (such as compiled code) and large static files (images, videos) out of the repository to not exceed storage limits and keep push/pull operations lean and fast. Mid-term, we should look for a solution to not commit images. File hosting would be the classic thing to consider in this regard.

I think we are nearly there considering the new iteration of the page. Keep up the good work!

**Comment by softbobo** [comment]
Just checked the last set of commits. I think we can merge this after we added hyperlinks to artist infos in the __interventions__ section. Content looks complete to me, is it @masssamasssa ?

**Comment by masssamasssa** [comment]
@softbobo, not ready yet. 

The following things are still missing:

- Final pictures. If nothing lands within the next days, we can use placeholders for version 1.0 and update later
- Optional label/crew info next to artist names for Intervention and Closing section to add give more detailed info
- Hyperlinks to artists
- Hyperlinks to location addresses
- Links to individual sections within the Routines description text
- "W"-Browser-Tab-Logo
- "Periphery"-Text/Info

**Comment by softbobo** [comment]
LGTM - good job @philorilla and @masssamasssa

**Pull request merged**
